import {Router} from 'express'; import {z} from 'zod'; import {prisma} from '../server'; import {requireAuth,requireRoles} from '../middleware/auth'; import {Role} from '@prisma/client';
const r=Router(); const admin= [Role.SUPER_ADMIN,Role.ADMIN,Role.TEACHER];
const classSchema=z.object({name:z.string().min(1),slug:z.string().min(1),category:z.string().default('SCHOOL'),board:z.string().optional(),level:z.string().optional(),description:z.string().optional(),thumbnailUrl:z.string().optional(),active:z.boolean().optional(),sortOrder:z.number().int().optional()});
r.get('/classes',async(_q,res)=>res.json(await prisma.class.findMany({where:{active:true},orderBy:{sortOrder:'asc'}})));
r.post('/classes',requireAuth,requireRoles(...admin),async(req,res)=>{const d=classSchema.parse(req.body);res.status(201).json(await prisma.class.create({data:d}))});
r.put('/classes/:id',requireAuth,requireRoles(...admin),async(req,res)=>{res.json(await prisma.class.update({where:{id:req.params.id},data:req.body}))});
r.delete('/classes/:id',requireAuth,requireRoles(Role.SUPER_ADMIN,Role.ADMIN),async(req,res)=>{await prisma.class.delete({where:{id:req.params.id}});res.json({ok:true})});
r.get('/classes/:id/subjects',async(req,res)=>res.json(await prisma.subject.findMany({where:{classId:req.params.id,active:true},orderBy:{sortOrder:'asc'}})));
r.post('/subjects',requireAuth,requireRoles(...admin),async(req,res)=>res.status(201).json(await prisma.subject.create({data:req.body})));
r.put('/subjects/:id',requireAuth,requireRoles(...admin),async(req,res)=>res.json(await prisma.subject.update({where:{id:req.params.id},data:req.body})));
r.delete('/subjects/:id',requireAuth,requireRoles(Role.SUPER_ADMIN,Role.ADMIN),async(req,res)=>{await prisma.subject.delete({where:{id:req.params.id}});res.json({ok:true})});
r.get('/subjects/:id/chapters',async(req,res)=>res.json(await prisma.chapter.findMany({where:{subjectId:req.params.id},orderBy:{sortOrder:'asc'}})));
r.post('/chapters',requireAuth,requireRoles(...admin),async(req,res)=>res.status(201).json(await prisma.chapter.create({data:req.body})));
r.put('/chapters/:id',requireAuth,requireRoles(...admin),async(req,res)=>res.json(await prisma.chapter.update({where:{id:req.params.id},data:req.body})));
r.delete('/chapters/:id',requireAuth,requireRoles(Role.SUPER_ADMIN,Role.ADMIN),async(req,res)=>{await prisma.chapter.delete({where:{id:req.params.id}});res.json({ok:true})});
r.get('/chapters/:id/lessons',async(req,res)=>res.json(await prisma.lesson.findMany({where:{chapterId:req.params.id},orderBy:{createdAt:'asc'}})));
r.post('/lessons',requireAuth,requireRoles(...admin),async(req,res)=>res.status(201).json(await prisma.lesson.create({data:req.body})));
r.put('/lessons/:id',requireAuth,requireRoles(...admin),async(req,res)=>res.json(await prisma.lesson.update({where:{id:req.params.id},data:req.body})));
r.delete('/lessons/:id',requireAuth,requireRoles(Role.SUPER_ADMIN,Role.ADMIN),async(req,res)=>{await prisma.lesson.delete({where:{id:req.params.id}});res.json({ok:true})});
export default r;
